### ISSUE TITLE
Compile error with ExMoney

### ISSUE THREAD

**Issue by hl** [elixir-cldr/cldr_utils#3]
ex_money 5.0.2
cldr_utils 2.9.0

```
== Compilation error in file lib/money/currency.ex ==
** (FunctionClauseError) no function clause matching in Cldr.Map.atomize_keys/2    
    
    The following arguments were given to Cldr.Map.atomize_keys/2:
    
        # 1
        1
    
        # 2
        []
    
    Attempted function clauses (showing 2 out of 2):
    
        def atomize_keys(map, options) when is_map(map) or is_list(map)
        def atomize_keys({k, value}, options) when is_map(value) or is_list(value)
    
    lib/cldr/utils/map.ex:207: Cldr.Map.atomize_keys/2
    lib/cldr/config/config.ex:1290: anonymous fn/2 in Cldr.Config.atomize_keys/2
    (elixir 1.10.3) lib/enum.ex:1400: anonymous fn/3 in Enum.map/2
    (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
    (elixir 1.10.3) lib/enum.ex:2127: Enum.map/2
    lib/cldr/config/config.ex:1288: Cldr.Config.atomize_keys/2
    lib/cldr/config/config.ex:1274: Cldr.Config.do_get_locale/3
    lib/cldr/compiler_locale_cache.ex:71: Cldr.Locale.Cache.do_get_locale/2
could not compile dependency :ex_money, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_money", update it with "mix deps.update ex_money" or clean it with "mix deps.clean ex_money"
```

**Comment by kipcole9** [comment]
Apologies for the inconvenience. Fixed with [this commit](https://github.com/elixir-cldr/cldr_utils/commit/c6e4996bb06a913d42ce9e6f275b24c7a29b6e36).

* Published [cldr_utils version 2.9.1](https://hex.pm/packages/cldr_utils/2.9.1)
* Retired `cldr_utils` version 2.9.0

Please `mix hex.update cldr_utils` and I believe you will be good to go.

Thanks for the report.

**Comment by hl** [comment]
No inconvenience at all. Thank you for your amazing libraries.

**Comment by ericdude4** [comment]
@kipcole9 Getting this error, could it be related?
```
== Compilation error in file lib/xyz/shared/cldr.ex ==
** (FunctionClauseError) no function clause matching in Cldr.Map.atomize_values/2    
    
    The following arguments were given to Cldr.Map.atomize_values/2:
    
        # 1
        "hanidec"
    
        # 2
        [only_existing: false]
    
    Attempted function clauses (showing 2 out of 2):
    
        def atomize_values(map, options) when is_map(map) or is_list(map)
        def atomize_values({k, value}, options) when is_map(value) or is_list(value)
    
    (cldr_utils 2.17.1) lib/cldr/utils/map.ex:349: Cldr.Map.atomize_values/2
    (ex_cldr 2.27.1) lib/cldr/locale/loader.ex:146: anonymous fn/1 in Cldr.Locale.Loader.structure_date_formats/1
    (cldr_utils 2.17.1) lib/cldr/utils/map.ex:182: anonymous fn/5 in Cldr.Map.deep_map/4
    (stdlib 3.17) maps.erl:410: :maps.fold_1/3
    (cldr_utils 2.17.1) lib/cldr/utils/map.ex:159: Cldr.Map.deep_map/4
    (cldr_utils 2.17.1) lib/cldr/utils/map.ex:166: anonymous fn/5 in Cldr.Map.deep_map/4
    (stdlib 3.17) maps.erl:410: :maps.fold_1/3
    (cldr_utils 2.17.1) lib/cldr/utils/map.ex:159: Cldr.Map.deep_map/4
```

**Comment by kipcole9** [comment]
@ericdude4, sorry for the slow response (caught COVID). I believe this is likely happening when you have a "later" version of `ex_cldr` and an "earlier" version of `ex_money`.  For each project I can define the minimum package requirement for dependencies.  But I can't retrofit a maximum release value (that I'm aware of).  My guess is that if you upgrade `ex_money` and then get dependencies the issue will go away.

Can you show the contents of your `mix.lock` file so I can delve deeper?

**Comment by kipcole9** [comment]
Ah, just noticed you put the versions in your post (I need more coffee). It reinforces my belief that upgrading `ex_money` will resolve the issue (the latest version is [ex_money 5.9.0](https://hex.pm/packages/ex_money/5.9.0).

**Comment by ericdude4** [comment]
Hi @kipcole9, thank you for your response, I wish you a quick recovery from your illness!

I was in fact running the most recent versions of these libraries. Another clue: this only happens when I am running with `MIX_ENV=test`. `mix compile` in dev mode works fine, in test - no luck.

Here is the `mix.lock` for all of the `cldr` based libraries I am using:
```
"ex_cldr": {:hex, :ex_cldr, "2.27.1", "b4fdedc29d6566b5201aea9bb7b554db16ac7b30366188aa0c50790b4393c268", [:mix], [{:castore, "~> 0.1", [hex: :castore, repo: "hexpm", optional: true]}, {:certifi, "~> 2.5", [hex: :certifi, repo: "hexpm", optional: true]}, {:cldr_utils, "~> 2.17", [hex: :cldr_utils, repo: "hexpm", optional: false]}, {:decimal, "~> 1.6 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:gettext, "~> 0.19", [hex: :gettext, repo: "hexpm", optional: true]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:nimble_parsec, "~> 0.5 or ~> 1.0", [hex: :nimble_parsec, repo: "hexpm", optional: true]}, {:plug, "~> 1.9", [hex: :plug, repo: "hexpm", optional: true]}], "hexpm", "b5c5c31fb7cf43d47e1267a7ede8e46c2cf12de3308ea1ba614241bd29bdcebf"},
"ex_cldr_currencies": {:hex, :ex_cldr_currencies, "2.13.0", "13188b99e527d724ed3dc2af37e54f0dac42dec42b620a34c4ed4d4902fad6dd", [:mix], [{:ex_cldr, "~> 2.24", [hex: :ex_cldr, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm", "64731e49ac3530aa88872b52c319eb5231bfb1a3ebb0956044c34abc0ed4f520"},
"ex_cldr_numbers": {:hex, :ex_cldr_numbers, "2.25.2", "9bd1f21bb7a300e1e0fd080b99f0c912d2adf90292e7d7c0335a6da84758c8a8", [:mix], [{:decimal, "~> 1.6 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:ex_cldr, "~> 2.26", [hex: :ex_cldr, repo: "hexpm", optional: false]}, {:ex_cldr_currencies, "~> 2.13", [hex: :ex_cldr_currencies, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm", "5de180d21018797bc412aae727402b3004df4c5666ed2602863448993b035c9b"},
"ex_cldr_territories": {:hex, :ex_cldr_territories, "2.4.0", "01e96157277e3ebf5dae242bbbe1c93096922acd0edc1a0d82f81d9ac11c06f0", [:mix], [{:ex_cldr, "~> 2.26", [hex: :ex_cldr, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm", "a57d182d2c934a91cc2157c5a0a201eb5659874578c12ef9cadcac6391d37b8a"},
"ex_money": {:hex, :ex_money, "5.9.0", "14ec07a0e950bc8ffdecfe3227e48010e7f97d1e12112f80cb62157ed8806373", [:mix], [{:castore, "~> 0.1", [hex: :castore, repo: "hexpm", optional: true]}, {:certifi, "~> 2.5", [hex: :certifi, repo: "hexpm", optional: true]}, {:decimal, "~> 1.6 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:ex_cldr_numbers, "~> 2.23", [hex: :ex_cldr_numbers, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:nimble_parsec, "~> 0.5 or ~> 1.0", [hex: :nimble_parsec, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 2.0 or ~> 3.0", [hex: :phoenix_html, repo: "hexpm", optional: true]}], "hexpm", "9ef44a58b468f32d19f4707f81ead03f93d3e669cb0abda02e60aa6a927150d4"},
"ex_money_sql": {:hex, :ex_money_sql, "1.6.0", "6b9e59f88c8a1ca22762ae482b529833ba576f4b67f5c58a98f59a05b4c32de9", [:mix], [{:ecto, "~> 3.5", [hex: :ecto, repo: "hexpm", optional: false]}, {:ecto_sql, "~> 3.0", [hex: :ecto_sql, repo: "hexpm", optional: false]}, {:ex_money, "~> 5.7", [hex: :ex_money, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: false]}, {:postgrex, "~> 0.15", [hex: :postgrex, repo: "hexpm", optional: false]}], "hexpm", "185897877613ff08fe7fc1b67c10ade3fab80cb17fcd897099a36bd6996412ba"},
```

**Comment by kipcole9** [comment]
I'm back on line, just.

The symptoms you describe suggest that somehow the locale files have got out of sync with the `ex_cldr` release.  Have you tried deleting the `test` build directory? (or just the entire `_build` directory tree to ensure a baseline).  

Locale files being out of sync can happen with some CI/CD caching strategies. Locale files aren't always format compatible across releases of `ex_cldr` and it happens that the change of some of the `Cldr.LanguageTag` fields to be atom based meant that the locale data in `ex_cldr` 2.27 is different to that in 2.26.

If this sounds like your situation then you can add `force_locale_download: true` in your backend configuration in test mode like this:
```elixir
defmodule MyApp.Cldr do
  use Cldr, 
    locales: ["en", "fr", "ja", "ar"],
    default_locale: ["en"],
    providers: [Cldr.Number, Money],
    force_locale_download: (Mix.env() == :test)
end
```
This will ensure that the correct locale version is always used in `:test` mode, irrespective of CI/CD caching mode. Of course that might not be desirable for your use case and revisiting the artefact caching strategy in your CI/CD might be a better approach.

Hope this at least describes the most likely way you are getting no compilation errors in `:dev` but you are in `:test`.  If deleting the `_build` tree doesn't result in a clean compile (or setting `force_locale_download: Mix.env() == :test`) then something very strange is going on and we'll need to keep digging.

**Comment by kipcole9** [comment]
PS: I built a test app with the exact versions from your lock file and had no compilation issues in `:dev` or `:test` so I don't think there is an overall compatibility issue (and these are the versions I use in my internal CI/CD too).
